### ISSUE TITLE
Motorsteuerung

### ISSUE THREAD

**Issue by MokkaGnom** [DronesTowerDefence/Arduino#4]
Es fehlt noch das Bremsen / Rückwärtsfahren wie besprochen.

Wenn das erste Mal eine 2 kommt soll solange gebremst werden, bis das Auto still steht, dann muss eine 0 kommen und wenn dann eine 2 kommt soll das Auto Rückwärts fahren.

**Comment by SILVERFIELD19** [comment]
Da hast du

**Comment by SILVERFIELD19** [comment]
Da hast du
